[unstable]
host-config = true
target-applies-to-host = true

[build]
target = "aarch64-linux-android"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
strip = "symbols"

[profile.release.build-override]
opt-level = 3

[host."x86_64-unknown-linux-gnu"]
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=lld"]

[target."aarch64-linux-android"]
rustflags = ["-C", "target-cpu=kryo", "-C", "target-feature=+fp16,+lse", "-C", "link-arg=-fuse-ld=lld"]

[target."x86_64-unknown-linux-gnu"]
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=lld"]

[registries.crates-io]
protocol = "sparse"

[env]
CFLAGS = "--target=aarch64-linux-android29 -O3 -march=armv8-a+crypto+fp16+lse -mcpu=kryo -pipe"
CXXFLAGS = "--target=aarch64-linux-android29 -O3 -march=armv8-a+crypto+fp16+lse -mcpu=kryo -pipe"
LDFLAGS = "-fuse-ld=lld -Wl,-O2 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed"
BUILD_CFLAGS = "--target=x86_64-unknown-linux-gnu -O3 -march=native -pipe"
BUILD_CXXFLAGS = "--target=x86_64-unknown-linux-gnu -O3 -march=native -pipe"
BUILD_LDFLAGS = "-fuse-ld=lld -Wl,-O2 -Wl,-z,relro -Wl,-z,now -Wl,--as-needed"
CFLAGS_aarch64_linux_android = "--target=aarch64-linux-android29 -O3 -flto=thin -march=armv8-a+crypto+fp16+lse -mcpu=kryo -fsplit-lto-unit -pipe"
CXXFLAGS_aarch64_linux_android = "--target=aarch64-linux-android29 -O3 -flto=thin -march=armv8-a+crypto+fp16+lse -mcpu=kryo -fsplit-lto-unit -pipe"
CFLAGS_x86_64_unknown_linux_gnu = "--target=x86_64-unknown-linux-gnu -O3 -flto=thin -march=native -fsplit-lto-unit -pipe"
CXXFLAGS_x86_64_unknown_linux_gnu = "--target=x86_64-unknown-linux-gnu -O3 -flto=thin -march=native -fsplit-lto-unit -pipe"
CXXSTDLIB = "c++"

V8_FROM_SOURCE = "1"
GN_ARGS = """\
host_os="linux" \
host_cpu="x64" \
target_os="android" \
target_cpu="arm64" \
custom_toolchain="//build/toolchain/android:android_clang_arm64" \
host_toolchain="//build/toolchain/linux:clang_x64_v8_arm64" \
v8_snapshot_toolchain="//build/toolchain/linux:clang_x64_v8_arm64" \
clang_version="14" \
android_ndk_root="/opt/android-ndk-r25c" \
android_ndk_version="r25c" \
android_ndk_major_version=25 \
android32_ndk_api_level=29 \
android64_ndk_api_level=29 \
android_channel="stable" \
is_official_build=true \
is_chrome_branded=true \
is_high_end_android=true \
optimize_for_size=false \
is_component_build=false \
use_custom_libcxx=false \
use_chromium_rust_toolchain=false \
use_thin_lto=false \
is_debug=false \
symbol_level=0 \
v8_symbol_level=0 \
strip_debug_info=true \
is_cfi=false \
arm_control_flow_integrity="none" \
chrome_pgo_phase=0 \
enable_resource_allowlist_generation=false \
v8_builtins_profiling_log_file="" \
v8_advanced_bigint_algorithms=true \
v8_use_siphash=true\
"""
